apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: eu.gcr.io/ptcs-docker-registry/jenkinsci/jenkins:1.00
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts: 
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: configgi
          mountPath: /var/jenkins_home/configs
        - name: credentiaalit
          mountPath: /var/jenkins_home/credentials
        - name: pluginit
          mountPath: /var/jenkins_home/pluginit
      volumes:
      - name: docker-socket
        hostPath: 
          path: /var/run/docker.sock
      - name: configgi
        configMap: 
          name: config-xml
      - name: credentiaalit
        configMap: 
          name: credentials-xml
      - name: pluginit
        configMap: 
          name: plugins-txt