kind: PersistentVolume
apiVersion: v1
metadata: 
  name: jenkins-pv
  labels: 
    type: hostpath
spec: 
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/jenkins-data
    