apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: docker.io/ptcos/ci-jenkins-master:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts: 
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: pluginit
          mountPath: /var/jenkins_home/pluginit
        - name: jenkins-volume
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-volume
        hostPath: 
          path: /data/jenkins-data
      - name: docker-socket
        hostPath: 
          path: /var/run/docker.sock
      - name: pluginit
        configMap: 
          name: plugins-txt