FROM alpine:3.5

ENV DOCKER_HOST unix:///var/run/docker.sock
ARG DOCKER_PATH="/usr/bin"
ARG DOCKER_VERSION="1.11.2"
ARG DOCKER_URI="https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz"
ARG KUBECTL_VERSION="1.7.2"
ENV DOCKER_API_VERSION="1.23"

USER root

RUN apk update && \
    apk add curl openssh-client && \
    rm -rf /var/cache/apk/* && \
    curl ${DOCKER_URI} -o /tmp/docker-${DOCKER_VERSION}.tgz && \
    cd /tmp && \
    curl ${DOCKER_URI}.sha256 -o - | sha256sum -c - && \
    tar -xvzf /tmp/docker-${DOCKER_VERSION}.tgz docker/docker && \
    mv -v docker/docker ${DOCKER_PATH}/docker && \
    rmdir -v docker && \
    rm -v /tmp/docker-${DOCKER_VERSION}.tgz && \
    chmod -v +x ${DOCKER_PATH}/docker && \
    curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl && \
    chmod -v +x /usr/local/bin/kubectl && \
    addgroup -S docker && \
    adduser -S -G docker docker && \
    adduser -G docker -u 10000 -D jenkins

USER jenkins
